services:
  perfect-pic:
    image: ghcr.io/goodboyboy666/perfect-pic-server:latest
    container_name: perfect-pic
    ports:
      - "8080:8080"
    volumes:
      - ./config:/data/config
      - ./database:/data/database
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
